// ERNA gull- og silfursmiðja — all copy, is + en.
// Every price, year, name and dimension below is lifted verbatim from erna.is
// (WordPress REST API, read 2026-07-25). Nothing invented. No em-dashes.

export const SITE = {
  brand: 'ERNA',
  brandFull: 'ERNA gull- og silfursmiðja',
  address: 'Skipholt 3, 105 Reykjavík',
  street: 'Skipholt 3',
  postal: '105',
  city: 'Reykjavík',
  phone: '552 0775',
  phoneTel: '+3545520775',
  phoneAlt: '696 4626',
  phoneAltTel: '+3546964626',
  phoneAlt2: '616 1200',
  email: 'erna@erna.is',
  instagram: 'erna.reykjavik',
  instagramUrl: 'https://www.instagram.com/erna.reykjavik/',
  founded: '1924-02-03',
  foundedYear: '1924',
  thisYear: '2026',
  founder: 'Guðlaugur A. Magnússon',
  founderYears: '1902 til 1952',
  director: 'Sara Steina',
  origin: 'https://erna.is',
};

const marks = [
  {
    code: 'GAM',
    img: 'gam-hringur.webp',
    who: 'Guðlaugur A. Magnússon',
    life: '1902 til 1952',
    is: 'Upphafsstafir Guðlaugs undir rísandi sól, með hlutfallstölu sterling silfurs neðst. Tekinn í notkun 1946. Fram að því var stimpillinn, frá 1924, upphafsstafirnir GAM auk hreinleikastimpils.',
    en: 'The founder’s initials beneath a rising sun, with the sterling fineness below. In use from 1946. Before that, from 1924, the mark was GAM plus a fineness stamp.',
    altIs: 'GAM stimpill sleginn innan í gullhring hjá ERNU',
    altEn: 'The GAM maker’s mark struck inside a gold ring at ERNA',
  },
  {
    code: 'GB',
    img: 'gisli.webp',
    who: 'Guðjón Bernharðsson',
    life: '1901 til 1978',
    is: 'Rak silfursmiðju fyrst á Akureyri og síðar í Reykjavík. Árið 1960 sameinaðist smiðja hans Ernu hf. Sonur hans Gunnar teiknaði Rauðhettuskeiðina, sem er enn eftirsótt sjö áratugum síðar.',
    en: 'Ran a silver workshop first in Akureyri, later in Reykjavík. In 1960 his workshop merged into Erna hf. His son Gunnar drew the Rauðhetta spoon, still sought after seven decades later.',
    altIs: 'Nafnstimpill sleginn í gullmun, smámynd',
    altEn: 'A maker’s name struck into gold, macro photograph',
  },
  {
    code: 'SS',
    img: 'ak-stimpill.webp',
    who: 'Silfursmiðjan, Kornelíus Jónsson',
    life: '1915 til 2010',
    is: 'SS táknar Silfursmiðjuna sem nokkrir þekktir úra- og gullsmiðir ráku í Reykjavík. Kornelíus framleiddi nokkur af gömlu mynstrunum allt til 2010, þá tæplega 95 ára.',
    en: 'SS stands for Silfursmiðjan, run by several well known watch and goldsmiths in Reykjavík. Kornelíus kept producing some of the old patterns until 2010, aged almost 95.',
    altIs: 'Þrír slegnir stimplar: 830S, Made in Iceland og AK',
    altEn: 'Three struck punches: 830S, Made in Iceland and AK',
  },
];

const heirlooms = [
  {
    id: 'barnaskeidin',
    img: 'barnaskeidar.webp',
    year: '1936',
    is: {
      moment: 'Fyrsta silfrið',
      title: 'Barnaskeiðin',
      body: 'Frá 1936 hafa silfursmiðir ERNU handsmíðað íslenskar barnaskeiðar úr silfri. Fimm myndefni ganga enn: Klukkuskeiðin, Barnið, Svanur, Rauðhetta og Hans og Gréta.',
      price: '39.500 kr.',
      note: 'Eldri borgarar fá 10% afslátt og 30% af áletrun.',
      alt: 'Fimm handsmíðaðar íslenskar barnaskeiðar úr silfri, skaftendar með myndefni',
    },
    en: {
      moment: 'The first silver',
      title: 'The christening spoon',
      body: 'Since 1936 ERNA’s silversmiths have hand made Icelandic children’s spoons in silver. Five motifs are still in production: the clock, the child, the swan, Red Riding Hood, and Hansel and Gretel.',
      price: 'ISK 39,500',
      note: 'Seniors receive 10% off, and 30% off engraving.',
      alt: 'Five hand made Icelandic children’s spoons in silver, motif handle ends',
    },
  },
  {
    id: 'hringarnir',
    img: 'hringar.webp',
    year: '14K',
    is: {
      moment: 'Já',
      title: 'Trúlofunar- og giftingarhringar',
      body: 'Kúptir 3 mm hringar úr 14 karata gulli, handsmíðaðir á verkstæðinu í Skipholti. Verðið miðast við par með áletrun. Breiðari gerðir, demantar og tantalum fást einnig.',
      price: '159.000 kr. parið',
      note: 'Sendum málband til að mæla fingurstærðir.',
      alt: 'Tveir handsmíðaðir giftingarhringar úr gulli á steini',
    },
    en: {
      moment: 'Yes',
      title: 'Engagement and wedding rings',
      body: 'Domed 3 mm bands in 14 carat gold, hand forged in the Skipholt workshop. The price is for the pair, engraving included. Wider profiles, diamonds and tantalum are also available.',
      price: 'ISK 159,000 the pair',
      note: 'We post a measuring tape for ring sizes.',
      alt: 'Two hand forged gold wedding bands resting on stone',
    },
  },
  {
    id: 'gaffallinn',
    img: 'letrun.webp',
    year: 'Faber Islandicus',
    is: {
      moment: 'Fyrsta máltíðin',
      title: 'Brúðkaupsgaffallinn',
      body: 'Brúðhjónin borða sameiginlega með honum sem tákn um samstillta hugi og jöfnuð. Handsmíðaður úr ósviknu silfri, úr línunni Faber Islandicus. Hægt er að grafa stafi hjónanna á hjartað.',
      price: '37.500 kr.',
      note: 'Handgröftur frá 1.500 kr. á staf.',
      alt: 'Handgrafið blómamynstur í silfri, unnið á verkstæði ERNU',
    },
    en: {
      moment: 'The first meal',
      title: 'The wedding fork',
      body: 'The couple eat from it together, as a sign of shared minds and equal footing. Hand made in solid silver, from the Faber Islandicus line. The couple’s initials can be engraved on the heart.',
      price: 'ISK 37,500',
      note: 'Hand engraving from ISK 1,500 per character.',
      alt: 'Hand engraved floral work in silver, macro of an ERNA silversmith’s engraving',
    },
  },
  {
    id: 'stjarnan',
    img: 'studentastjarnan.webp',
    year: '925',
    is: {
      moment: 'Húfan',
      title: 'Stúdentastjarnan',
      body: 'Stjarnan með langri keðju, í silfri eða 14 karata gulli. Hún er gefin á þeim degi sem húfan kemur á höfuðið, og hún fer ekki af eftir það.',
      price: '14.500 kr. í silfri',
      note: '69.500 kr. í 14 karata gulli.',
      alt: 'Stúdentastjarnan úr silfri í keðju, hönnun ERNU',
    },
    en: {
      moment: 'The cap',
      title: 'The graduation star',
      body: 'The star on a long chain, in silver or 14 carat gold. It is given on the day the white cap goes on, and it tends not to come off afterwards.',
      price: 'ISK 14,500 in silver',
      note: 'ISK 69,500 in 14 carat gold.',
      alt: 'ERNA’s silver graduation star pendant on a chain',
    },
  },
  {
    id: 'jolaskeidin',
    img: 'jolaskeidin.webp',
    year: '79 ár',
    is: {
      moment: 'Ein á ári',
      title: 'Jólaskeiðin',
      body: 'Það eru 79 ár síðan fyrsta jólaskeiðin var smíðuð hjá ERNU, úr 925 sterling silfri á sama hátt og í byrjun. Núverandi sería er hönnuð af Ragnhildi Sif Reynisdóttur og þemað er tónlist. Skeiðin 2026 verður sú tólfta og jafnframt sú síðasta sem ERNA framleiðir.',
      price: '33.500 kr.',
      note: 'Til eldri borgara 29.500 kr.',
      alt: 'Jólaskeiðin 2024 úr 925 sterling silfri, gyllt skeiðarblað',
    },
    en: {
      moment: 'One a year',
      title: 'The Christmas spoon',
      body: 'It is 79 years since the first Christmas spoon was made at ERNA, in 925 sterling silver, the same way as at the start. The current series is designed by Ragnhildur Sif Reynisdóttir on a theme of music. The 2026 spoon will be the twelfth, and the last ERNA produces.',
      price: 'ISK 33,500',
      note: 'ISK 29,500 for seniors.',
      alt: 'The 2024 Christmas spoon in 925 sterling silver with a gilded bowl',
    },
  },
];

const steps = [
  {
    key: 'silfrid',
    n: '01',
    img: 'matsett.webp',
    is: {
      word: 'silfrið',
      title: '925',
      body: 'Sterling silfur og ekkert annað. Framleiðsla á íslenskum silfurborðbúnaði hófst á verkstæðinu 1936, og mynstrin frá þeim árum eru enn smíðuð: Erna, Kaktus, Renaissance, Reykjavík, Vor og Smári.',
      alt: 'Reykjavík matsett úr 925 sterling silfri, hnífur, gaffall og skeið',
    },
    en: {
      word: 'the silver',
      title: '925',
      body: 'Sterling silver and nothing else. Production of Icelandic silver flatware began in the workshop in 1936, and the patterns from those years are still made: Erna, Kaktus, Renaissance, Reykjavík, Vor and Smári.',
      alt: 'The Reykjavík flatware set in 925 sterling silver, knife, fork and spoon',
    },
  },
  {
    key: 'eldurinn',
    n: '02',
    img: 'eldurinn.webp',
    is: {
      word: 'eldurinn',
      title: 'Handsmíðað',
      body: 'Silfrið er brætt í deiglunni og hitað þar til það lætur undan. Það sem er handsmíðað fer í gegnum hendur áður en það fer í kassa. Verkstæðið hefur staðið á sama stað í Skipholti í áratugi.',
      alt: 'Logsuðulogi bræðir glóandi silfur í deiglu á verkstæði ERNU',
    },
    en: {
      word: 'the fire',
      title: 'Hand forged',
      body: 'The silver is melted in the crucible and heated until it gives. What is hand made passes through hands before it passes into a box. The workshop has stood in the same place in Skipholt for decades.',
      alt: 'A torch flame melting glowing silver in a crucible at ERNA’s workshop',
    },
  },
  {
    key: 'stimpillinn',
    n: '03',
    img: 'stimpillinn.webp',
    is: {
      word: 'stimpillinn',
      title: 'Eitt högg',
      body: 'Í lokin er stimpillinn sleginn. GAM undir rísandi sól, með hlutfallstöluna 925 neðst. Sá stimpill hefur verið í notkun síðan 1946. Eftir það á hluturinn sér sögu sem hægt er að lesa.',
      alt: 'Slitið stálstimpilverkfæri á vinnuborði silfursmiðs',
    },
    en: {
      word: 'the hallmark',
      title: 'One blow',
      body: 'At the end the punch is struck. GAM beneath a rising sun, with the fineness 925 below. That mark has been in use since 1946. After it, the object has a history that can be read.',
      alt: 'A worn steel punch tool on a silversmith’s bench',
    },
  },
];

const timeline = [
  { y: '1924', is: 'Guðlaugur A. Magnússon setur á stofn verkstæði á Ísafirði, 3. febrúar.', en: 'Guðlaugur A. Magnússon opens a workshop in Ísafjörður on 3 February.' },
  { y: '1927', is: 'Verkstæðið flyst til Reykjavíkur, með viðkomu í Hafnarfirði.', en: 'The workshop moves to Reykjavík, by way of Hafnarfjörður.' },
  { y: '1936', is: 'Framleiðsla á silfurborðbúnaði hefst, og þar á meðal jólaskeiðunum.', en: 'Silver flatware production begins, the Christmas spoons among it.' },
  { y: '1946', is: 'Stimpillinn GAM undir rísandi sól, með 925 neðst, er tekinn í notkun.', en: 'The GAM mark beneath a rising sun, 925 below, comes into use.' },
  { y: '1947', is: 'Framleiðslan verður hlutafélag undir nafninu Erna, eftir Jónínu Ernu, dóttur Guðlaugs.', en: 'Production becomes a company named Erna, after Jónína Erna, Guðlaugur’s daughter.' },
  { y: '1960', is: 'Silfursmiðja Guðjóns Bernharðssonar sameinast Ernu hf.', en: 'Guðjón Bernharðsson’s silver workshop merges into Erna hf.' },
  { y: '2026', is: 'Þriðja og fjórða kynslóð fjölskyldunnar er við störf í Skipholti 3.', en: 'The third and fourth generation of the family are at work in Skipholt 3.' },
];

const priceList = [
  { g: 'is', group: 'Hringar' },
  { img: 'hringur-5mm.webp', is: ['14k gull, kúpt par 5 mm', '248.500'], en: ['14k gold, domed pair 5 mm', '248,500'], alt: { is: 'Par af handsmíðuðum giftingarhringum úr 14 karata gulli', en: 'A pair of hand forged 14 carat gold wedding bands' } },
  { img: 'hringur-demantar.webp', is: ['14k par 6 mm með 3x1p demöntum', '340.500'], en: ['14k pair 6 mm with 3x1pt diamonds', '340,500'], alt: { is: 'Giftingarhringar úr hvítu og gulu gulli með þremur demöntum', en: 'Wedding bands in white and yellow gold set with three diamonds' } },
  { img: 'tantalum.webp', is: ['Tantalum par 4 mm, hápólerað', '85.000'], en: ['Tantalum pair 4 mm, high polish', '85,000'], alt: { is: 'Par af hápóleruðum tantalum hringum, dökkur málmur', en: 'A pair of high polished tantalum bands, a dark metal' } },
  { g: 'is', group: 'Borðbúnaður' },
  { img: 'matsett.webp', is: ['Matskeið, 925 sterling silfur', '45.500'], en: ['Table spoon, 925 sterling silver', '45,500'], alt: { is: 'Reykjavík matsett úr sterling silfri', en: 'The Reykjavík flatware set in sterling silver' } },
  { img: 'islandsskeid.webp', is: ['Íslandsskeiðin', '175.500'], en: ['The Íslandsskeið spoon', '175,500'], alt: { is: 'Íslandsskeiðin með grafnu skafti', en: 'The Íslandsskeið spoon with engraved handle' } },
  { img: 'serviettuhringur.webp', is: ['Servíettuhringur, handgrafinn', 'sjá verðskrá'], en: ['Napkin ring, hand engraved', 'see price list'], alt: { is: 'Handgrafinn servíettuhringur úr silfri með blágresi', en: 'Hand engraved silver napkin ring with a cranesbill motif' } },
  { g: 'is', group: 'Söfnunarmunir' },
  { img: 'barnaskeidar.webp', is: ['Barnaskeið úr silfri, handsmíðuð', '39.500'], en: ['Silver children’s spoon, hand made', '39,500'], alt: { is: 'Íslenskar barnaskeiðar úr silfri', en: 'Icelandic children’s spoons in silver' } },
  { img: 'jolaskeid-2025.webp', is: ['Jólaskeiðin 2025', '33.500'], en: ['The 2025 Christmas spoon', '33,500'], alt: { is: 'Jólaskeiðin 2025 úr 925 sterling silfri, hönnun Ragnhildar Sifjar Reynisdóttur', en: 'The 2025 Christmas spoon in 925 sterling silver, designed by Ragnhildur Sif Reynisdóttir' } },
  { img: 'jolabjalla.webp', is: ['Jólabjallan 2024', '4.500'], en: ['The 2024 Christmas bell', '4,500'], alt: { is: 'Jólabjallan 2024 úr silfri, hönnun Aspar Ásgeirsdóttur', en: 'The 2024 Christmas bell in silver, designed by Ösp Ásgeirsdóttir' } },
  { g: 'is', group: 'Á heimilinu' },
  { img: 'stjaki.webp', is: ['Kertastjaki, 5 arma, gegnheilt silfur', '850.000'], en: ['Candelabrum, five arms, solid silver', '850,000'], alt: { is: 'Fimm arma kertastjaki úr gegnheilu silfri', en: 'A five arm candelabrum in solid silver' } },
  { img: 'thrikrossinn.webp', is: ['Þríkrossinn, silfur, stærð 1', '39.500'], en: ['The Þríkross, silver, size 1', '39,500'], alt: { is: 'Þríkrossinn, hannaður af Ásgeiri Gunnarssyni', en: 'The Þríkross, designed by Ásgeir Gunnarsson' } },
  { img: 'drekaskeid.webp', is: ['Drekaskeiðin', 'sjá verðskrá'], en: ['The dragon spoon', 'see price list'], alt: { is: 'Drekaskeiðin, skrautskeið úr silfri', en: 'The dragon spoon, an ornamental silver spoon' } },
];

export const COPY = {
  is: {
    lang: 'is',
    dir: '/',
    other: { code: 'en', href: '/en/', label: 'EN' },
    title: 'ERNA gull- og silfursmiðja | Skipholt 3, Reykjavík',
    description:
      'Handsmíðað íslenskt silfur og gull síðan 1924. Trúlofunarhringar, barnaskeiðar, jólaskeiðin og silfurborðbúnaður frá verkstæðinu í Skipholti 3. Sama fjölskyldan í 102 ár.',
    skip: 'Fara beint í efni',
    nav: [
      { href: '#gengur-a-milli', label: 'Verkin' },
      { href: '#smidin', label: 'Smíðin' },
      { href: '#stimpillinn', label: 'Stimpillinn' },
      { href: '#sagan', label: 'Sagan' },
      { href: '#verdskra', label: 'Verðskrá' },
    ],
    navCta: 'Hafa samband',
    loader: { top: '1924', bottom: '2026', mid: 'gull- og silfursmiðja' },
    hero: {
      wordmark: 'ERNA',
      standfirst: 'gull- og silfursmiðja',
      meta: ['Skipholt 3, Reykjavík', 'stofnað 3. febrúar 1924'],
      alt: 'Hvítir bómullarhanskar halda á handsmíðuðu úri frá ERNU',
    },
    thesis: {
      // two-speed reveal: c = caps (mask slide), i = italic lowercase (fade)
      title: [
        { c: 'HLUTIRNIR' }, { i: 'sem' }, { c: 'MARKA' }, { i: 'íslenskt' }, { c: 'LÍF' },
      ],
      body: 'Barnaskeiðin. Trúlofunarhringurinn. Brúðkaupsgaffallinn. Stúdentastjarnan. Jólaskeiðin sem safnast ein á ári í áratugi. Þetta eru ekki vörur. Þetta eru hlutirnir sem ganga á milli kynslóða í íslenskum fjölskyldum, og verkstæðið sem smíðar þá hefur staðið í Skipholti 3 síðan Guðlaugur A. Magnússon setti það á stofn 1924.',
      pull: 'Með góðri umhirðu endist íslenski silfurborðbúnaðurinn í kynslóðir.',
      pullSource: 'erna.is',
      cta: { label: 'Sjá verkin', href: '#gengur-a-milli' },
    },
    heirlooms: {
      title: [{ c: 'ÞAÐ' }, { i: 'sem gengur á' }, { c: 'MILLI' }],
      lead: 'Fimm hlutir. Fimm augnablik í einni ævi. Allir handsmíðaðir í Skipholti.',
      items: heirlooms.map((h) => ({ id: h.id, img: h.img, year: h.year, ...h.is })),
    },
    process: {
      title: [{ c: 'SILFRIÐ.' }, { i: 'eldurinn.' }, { c: 'STIMPILLINN.' }],
      lead: 'Þrjú skref, óbreytt í áratugi.',
      steps: steps.map((s) => ({ key: s.key, n: s.n, img: s.img, ...s.is })),
      resolve: 'og hluturinn er merktur',
    },
    marks: {
      title: [{ c: 'EITT' }, { i: 'högg og hluturinn á sér' }, { c: 'SÖGU' }],
      lead: 'ERNA heldur úti opinni stimplasíðu: skrá yfir maður fyrir mann þá íslensku gull- og silfursmiði sem slógu sín eigin merki í málminn. Platan hér að ofan er prufuplata verkstæðisins, slegin með stimplum smiðanna sjálfra.',
      plateAlt: 'Prufuplata ERNU, slegin röðum af stimplum íslenskra gull- og silfursmiða',
      registerLabel: 'Úr stimplaskránni',
      items: marks.map((m) => ({ code: m.code, img: m.img, who: m.who, life: m.life, body: m.is, alt: m.altIs })),
      link: { label: 'Öll stimplaskráin á erna.is', href: 'https://erna.is/stimplasida/' },
    },
    story: {
      title: [{ c: 'SAMA' }, { i: 'fjölskyldan síðan' }, { c: '1924' }],
      founderCaption: 'Guðlaugur A. Magnússon, 1902 til 1952, stofnandi ERNU.',
      founderAlt: 'Ljósmynd af Guðlaugi A. Magnússyni, stofnanda ERNU',
      lead: 'Guðlaugur byrjaði á Ísafirði. Reynir sonur hans byrjaði daginn eftir fermingu. Í dag eru þriðja og fjórða kynslóð fjölskyldunnar við störf, og framkvæmdastjóri er Sara Steina.',
      timeline: timeline.map((t) => ({ y: t.y, t: t.is })),
      quote: '„Gerum hversdaginn að hátíð en hátíðina aldrei hversdagslega."',
      quoteBy: 'Finn Schjøll, hönnuður. Tilvitnunin stendur á forsíðu erna.is.',
      archive: [
        { img: 'starfsfolk.webp', is: 'Starfsfólk á verkstæðinu, úr myndasafni ERNU.', alt: 'Fjögur úr starfsliði ERNU standa við steðjann á verkstæðinu' },
        { img: 'verkstaedi.webp', is: 'Silfursmiðir við bekkinn í Skipholti.', alt: 'Tveir silfursmiðir að störfum við vinnubekk með verkfærum' },
        { img: 'verkfaeri.webp', is: 'Verkfæraskrá smiðanna, handskrifuð.', alt: 'Handskrifuð skrá yfir verkfæri silfursmiðs, númeruð frá einum til ellefu' },
      ],
    },
    prices: {
      title: 'Verðskrá',
      lead: 'Úrval af því sem verkstæðið smíðar. Verð eru þau sem standa á erna.is í dag. Eldri borgarar fá 10% afslátt af íslenska silfurborðbúnaðinum.',
      colItem: 'Munur',
      colPrice: 'Verð, kr.',
      items: priceList.map((p) => (p.g ? { group: p.group } : { img: p.img, name: p.is[0], price: p.is[1], alt: p.alt.is })),
      note: 'Verðskráin er ekki tæmandi. Verkstæðið sérsmíðar einnig, tekur að sér viðgerðir, áletrun og mat á eðalmálmum, og smíðar nýja gripi úr gömlum.',
    },
    contact: {
      title: [{ c: 'KOMDU' }, { i: 'í' }, { c: 'SKIPHOLT 3' }],
      lead: 'Verkstæðið er opið milli 11:00 og 17:00 virka daga. Utan þess tíma er hægt að hringja.',
      noticeLabel: 'Athugið',
      notice: 'Verkstæðið er lokað frá 6. júlí til 4. ágúst vegna sumarleyfa.',
      rows: [
        { k: 'Heimilisfang', v: 'Skipholt 3, 105 Reykjavík' },
        { k: 'Sími', v: '552 0775', href: 'tel:+3545520775' },
        { k: 'Utan opnunartíma', v: '696 4626 og 616 1200', href: 'tel:+3546964626' },
        { k: 'Netfang', v: 'erna@erna.is', href: 'mailto:erna@erna.is' },
        { k: 'Opnunartími', v: 'Virka daga 11:00 til 17:00' },
        { k: 'Instagram', v: '@erna.reykjavik', href: 'https://www.instagram.com/erna.reykjavik/' },
      ],
      cta: { label: 'Senda póst', href: 'mailto:erna@erna.is' },
      cta2: { label: 'Hringja í 552 0775', href: 'tel:+3545520775' },
      shipping: 'Póstsendum um allt land með stuttum fyrirvara. Sendum málband til að mæla fingurstærðir.',
    },
    footer: {
      lines: ['ERNA gull- og silfursmiðja', 'Skipholt 3, 105 Reykjavík', 'Sími 552 0775'],
      years: '1924 til 2026',
      credit: 'Hugmynd að endurhönnun. SNDR Studio.',
      note: 'Óopinber hugmyndavinna, ekki í eigu eða á vegum ERNU.',
    },
  },

  en: {
    lang: 'en',
    dir: '/en/',
    other: { code: 'is', href: '/', label: 'ÍS' },
    title: 'ERNA gold and silversmith | Skipholt 3, Reykjavík',
    description:
      'Hand made Icelandic silver and gold since 1924. Wedding rings, christening spoons, the Christmas spoon and sterling flatware from the workshop at Skipholt 3. The same family for 102 years.',
    skip: 'Skip to content',
    nav: [
      { href: '#gengur-a-milli', label: 'The work' },
      { href: '#smidin', label: 'The making' },
      { href: '#stimpillinn', label: 'The mark' },
      { href: '#sagan', label: 'History' },
      { href: '#verdskra', label: 'Prices' },
    ],
    navCta: 'Contact',
    loader: { top: '1924', bottom: '2026', mid: 'gold and silversmith' },
    hero: {
      wordmark: 'ERNA',
      standfirst: 'gold and silversmith',
      meta: ['Skipholt 3, Reykjavík', 'founded 3 February 1924'],
      alt: 'White cotton gloves holding a hand made ERNA watch',
    },
    thesis: {
      title: [{ c: 'THE THINGS' }, { i: 'that mark an' }, { c: 'ICELANDIC LIFE' }],
      body: 'The christening spoon. The engagement ring. The wedding fork. The graduation star. The Christmas spoon, collected one a year for decades. These are not products. They are the objects Icelandic families hand down, and the workshop that makes them has stood at Skipholt 3 since Guðlaugur A. Magnússon founded it in 1924.',
      pull: 'With good care, Icelandic sterling flatware lasts for generations.',
      pullSource: 'erna.is',
      cta: { label: 'See the work', href: '#gengur-a-milli' },
    },
    heirlooms: {
      title: [{ c: 'WHAT' }, { i: 'gets handed' }, { c: 'DOWN' }],
      lead: 'Five objects. Five moments in one life. All hand made in Skipholt.',
      items: heirlooms.map((h) => ({ id: h.id, img: h.img, year: h.year, ...h.en })),
    },
    process: {
      title: [{ c: 'THE SILVER.' }, { i: 'the fire.' }, { c: 'THE MARK.' }],
      lead: 'Three steps, unchanged for decades.',
      steps: steps.map((s) => ({ key: s.key, n: s.n, img: s.img, ...s.en })),
      resolve: 'and the object is marked',
    },
    marks: {
      title: [{ c: 'ONE' }, { i: 'blow, and the object has a' }, { c: 'HISTORY' }],
      lead: 'ERNA keeps a public register of maker’s marks: a record, smith by smith, of the Icelandic gold and silversmiths who struck their own mark into metal. The plate above is the workshop’s own test plate, struck with the smiths’ punches.',
      plateAlt: 'ERNA’s test plate, struck with rows of Icelandic gold and silversmiths’ marks',
      registerLabel: 'From the register',
      items: marks.map((m) => ({ code: m.code, img: m.img, who: m.who, life: m.life, body: m.en, alt: m.altEn })),
      link: { label: 'The full register on erna.is', href: 'https://erna.is/stimplasida/' },
    },
    story: {
      title: [{ c: 'THE SAME' }, { i: 'family since' }, { c: '1924' }],
      founderCaption: 'Guðlaugur A. Magnússon, 1902 to 1952, founder of ERNA.',
      founderAlt: 'Photograph of Guðlaugur A. Magnússon, founder of ERNA',
      lead: 'Guðlaugur began in Ísafjörður. His son Reynir started the day after his confirmation. Today the third and fourth generation of the family are at work, and Sara Steina is managing director.',
      timeline: timeline.map((t) => ({ y: t.y, t: t.en })),
      quote: '“Make every ordinary day a feast, and never make the feast ordinary.”',
      quoteBy: 'Finn Schjøll, designer. The line appears on the front page of erna.is.',
      archive: [
        { img: 'starfsfolk.webp', is: 'Workshop staff, from ERNA’s own archive.', alt: 'Four of ERNA’s staff standing at the anvil in the workshop' },
        { img: 'verkstaedi.webp', is: 'Silversmiths at the bench in Skipholt.', alt: 'Two silversmiths at work at a bench covered in tools' },
        { img: 'verkfaeri.webp', is: 'The smiths’ tool register, hand written.', alt: 'A hand written register of a silversmith’s tools, numbered one to eleven' },
      ],
    },
    prices: {
      title: 'Price list',
      lead: 'A selection of what the workshop makes. Prices are those listed on erna.is today. Seniors receive 10% off the Icelandic sterling flatware.',
      colItem: 'Item',
      colPrice: 'Price, ISK',
      items: priceList.map((p) => (p.g ? { group: p.group } : { img: p.img, name: p.en[0], price: p.en[1], alt: p.alt.en })),
      note: 'The list is not exhaustive. The workshop also makes to commission, repairs, engraves, values precious metals, and makes new pieces from old.',
    },
    contact: {
      title: [{ c: 'COME' }, { i: 'to' }, { c: 'SKIPHOLT 3' }],
      lead: 'The workshop is open between 11:00 and 17:00 on weekdays. Outside those hours, call.',
      noticeLabel: 'Please note',
      notice: 'The workshop is closed from 6 July to 4 August for summer holidays.',
      rows: [
        { k: 'Address', v: 'Skipholt 3, 105 Reykjavík' },
        { k: 'Telephone', v: '552 0775', href: 'tel:+3545520775' },
        { k: 'Outside hours', v: '696 4626 and 616 1200', href: 'tel:+3546964626' },
        { k: 'Email', v: 'erna@erna.is', href: 'mailto:erna@erna.is' },
        { k: 'Opening hours', v: 'Weekdays 11:00 to 17:00' },
        { k: 'Instagram', v: '@erna.reykjavik', href: 'https://www.instagram.com/erna.reykjavik/' },
      ],
      cta: { label: 'Send an email', href: 'mailto:erna@erna.is' },
      cta2: { label: 'Call 552 0775', href: 'tel:+3545520775' },
      shipping: 'We post throughout Iceland at short notice, and send a measuring tape for ring sizes.',
    },
    footer: {
      lines: ['ERNA gold and silversmith', 'Skipholt 3, 105 Reykjavík', 'Telephone 552 0775'],
      years: '1924 to 2026',
      credit: 'Redesign concept. SNDR Studio.',
      note: 'An unofficial concept, not owned by or affiliated with ERNA.',
    },
  },
};
